### PR TITLE
Expose more contact fields and custom fields to columns

### PR DESCRIPTION
**Pull request by laryn**
For your consideration, this exposes more contact fields, and custom fields. It also changes the state/province field to use abbreviations rather than the full name.

### CODE REVIEW

**Comment by francescbassas** [comment]
What is the status of this PR? I am interested in using the extension but I see that it has not been updated for some time. Do you intend to keep it?

**Comment by MegaphoneJon** [comment]
@francescbassas I post almost every extension I write on Github, but unless they're posted in the extension directory, I don't intend to maintain them unless a client requests I do.  In this case, this was written for a client at my old company, so it's unlikely I'll ever update this on my own.  I trust Laryn's changes here, but haven't tested them myself.

That said, I *do* have intentions of reviewing and merging PRs that folks have taken the time to send to me.  I have new folks starting work with me next week; PR review will be part of their job, and I'll get through the backlog.

**Comment by francescbassas** [comment]
Sounds great @MegaphoneJon. Thanks for the response and for all your selfless work.

**Comment by MegaphoneJon** [comment]
@laryn Much delayed, but I finally got time to review this!  Thanks for your changes; I made some additional tweaks, and if you still use this you should upgrade to my master branch, because your master branch makes use of a now-removed function.  However, I took your version as the definitive branch when upgrading this, and it saved me quite a bit of time.

**Comment by MegaphoneJon** [comment]
@francescbassas I'm not sure if you get updates if I don't tag you - but the master branch here is now good to go.

**Comment by francescbassas** [comment]
Just downloaded 1.1 and installed. But launching report throughs this error...

`$Fatal Error Details = Array ( [callback] => Array ( [0] => CRM_Core_Error [1] => handle ) [code] => -19 [message] => DB Error: no such field [mode] => 16 [debug_info] => SELECT SQL_CALC_FOUND_ROWS contact_civireport.sort_name as civicrm_contact_sort_name, contact_civireport.id as civicrm_contact_id, contact_civireport.preferred_language as civicrm_contact_preferred_language, group_civireport.title as civicrm_group_title, DATE_FORMAT(MAX(subscription_history_civireport.date), '%Y-%m-%d') as civicrm_subscription_history_date, subscription_history_civireport.status as civicrm_subscription_history_status, subscription_history_civireport.method as civicrm_subscription_history_method, email_civireport.email as civicrm_email_email , group_civireport.group_id as civicrm_group_group_id FROM civicrm_subscription_history subscription_history_civireport LEFT JOIN civicrm_contact contact_civireport ON contact_civireport.id = subscription_history_civireport.contact_id LEFT JOIN civicrm_group group_civireport ON group_civireport.id = subscription_history_civireport.group_id LEFT JOIN civicrm_email email_civireport ON contact_civireport.id = email_civireport.contact_id AND email_civireport.is_primary = 1 WHERE contact_civireport.is_deleted = 0 GROUP BY contact_civireport.id, group_civireport.id ORDER BY subscription_history_civireport.date DESC, contact_civireport.sort_name ASC, group_civireport.group_id ASC LIMIT 0, 50 [nativecode=1054 ** Unknown column 'group_civireport.group_id' in 'field list'] [type] => DB_Error [user_info] => SELECT SQL_CALC_FOUND_ROWS contact_civireport.sort_name as civicrm_contact_sort_name, contact_civireport.id as civicrm_contact_id, contact_civireport.preferred_language as civicrm_contact_preferred_language, group_civireport.title as civicrm_group_title, DATE_FORMAT(MAX(subscription_history_civireport.date), '%Y-%m-%d') as civicrm_subscription_history_date, subscription_history_civireport.status as civicrm_subscription_history_status, subscription_history_civireport.method as civicrm_subscription_history_method, email_civireport.email as civicrm_email_email , group_civireport.group_id as civicrm_group_group_id FROM civicrm_subscription_history subscription_history_civireport LEFT JOIN civicrm_contact contact_civireport ON contact_civireport.id = subscription_history_civireport.contact_id LEFT JOIN civicrm_group group_civireport ON group_civireport.id = subscription_history_civireport.group_id LEFT JOIN civicrm_email email_civireport ON contact_civireport.id = email_civireport.contact_id AND email_civireport.is_primary = 1 WHERE contact_civireport.is_deleted = 0 GROUP BY contact_civireport.id, group_civireport.id ORDER BY subscription_history_civireport.date DESC, contact_civireport.sort_name ASC, group_civireport.group_id ASC LIMIT 0, 50 [nativecode=1054 ** Unknown column 'group_civireport.group_id' in 'field list'] [to_string] => [db_error: message="DB Error: no such field" code=-19 mode=callback callback=CRM_Core_Error::handle prefix="" info="SELECT SQL_CALC_FOUND_ROWS contact_civireport.sort_name as civicrm_contact_sort_name, contact_civireport.id as civicrm_contact_id, contact_civireport.preferred_language as civicrm_contact_preferred_language, group_civireport.title as civicrm_group_title, DATE_FORMAT(MAX(subscription_history_civireport.date), '%Y-%m-%d') as civicrm_subscription_history_date, subscription_history_civireport.status as civicrm_subscription_history_status, subscription_history_civireport.method as civicrm_subscription_history_method, email_civireport.email as civicrm_email_email , group_civireport.group_id as civicrm_group_group_id FROM civicrm_subscription_history subscription_history_civireport LEFT JOIN civicrm_contact contact_civireport ON contact_civireport.id = subscription_history_civireport.contact_id LEFT JOIN civicrm_group group_civireport ON group_civireport.id = subscription_history_civireport.group_id LEFT JOIN civicrm_email email_civireport ON contact_civireport.id = email_civireport.contact_id AND email_civireport.is_primary = 1 WHERE contact_civireport.is_deleted = 0 GROUP BY contact_civireport.id, group_civireport.id ORDER BY subscription_history_civireport.date DESC, contact_civireport.sort_name ASC, group_civireport.group_id ASC LIMIT 0, 50 [nativecode=1054 ** Unknown column 'group_civireport.group_id' in 'field list']"] ) `

**Comment by MegaphoneJon** [comment]
@francescbassas What report is this?

**Comment by francescbassas** [comment]
?¿
It's subscriptionhistory report.

**Comment by MegaphoneJon** [comment]
Sorry, of course!  I was tired and thought this was on the "nodrilldown" extension which I also recently updated.  Oh - and I think I know what the problem is - I must've fixed this locally but not pushed the update.  I'll check into this today.  Thanks for the bug report @francescbassas.

**Pull request merged**
